# Generated by Django 5.2.12 on 2026-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
