# Generated by Django 5.2.12 on 2026-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_deactivated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
