# Generated by Django 5.2.12 on 2026-04-08 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "lesson_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "variant",
                    models.CharField(
                        choices=[("base", "Base"), ("no_negatives", "No Negatives")],
                        default="base",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "resource_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("slide", "Slide"),
                            ("worksheet", "Worksheet"),
                            ("video", "Video"),
                            ("template", "Template"),
                            ("file", "File"),
                            ("link", "Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "category"],
            },
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_resources",
                        to="core.lesson",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_lessons",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="resources",
            field=models.ManyToManyField(
                related_name="lessons",
                through="core.LessonResource",
                to="core.resource",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("level", models.CharField(choices=[("gcse", "GCSE")], max_length=10)),
                (
                    "language",
                    models.CharField(choices=[("en", "English")], max_length=2),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "level", "language"),
                        name="unique_subject_title_level_language",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "curriculum_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculums",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "title"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "title"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="core.topic",
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "unit_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year_group",
                    models.CharField(
                        choices=[
                            ("year_7", "Year 7"),
                            ("year_8", "Year 8"),
                            ("year_9", "Year 9"),
                            ("year_10", "Year 10"),
                            ("year_11", "Year 11"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("red", "Red"),
                            ("amber", "Amber"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("mixed_ability", "Mixed Ability"),
                            ("general", "General"),
                            ("no_level_assigned", "No Level Assigned"),
                        ],
                        default="no_level_assigned",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.curriculum",
                    ),
                ),
            ],
            options={
                "ordering": ["curriculum", "year_group", "level", "order"],
            },
        ),
        migrations.CreateModel(
            name="UnitLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_units",
                        to="core.lesson",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_lessons",
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["unit", "order"],
            },
        ),
        migrations.AddField(
            model_name="unit",
            name="lessons",
            field=models.ManyToManyField(
                related_name="units", through="core.UnitLesson", to="core.lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonresource",
            constraint=models.UniqueConstraint(
                fields=("lesson", "resource"), name="unique_lesson_resource"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculum",
            constraint=models.UniqueConstraint(
                fields=("subject", "title"), name="unique_curriculum_title_per_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("subject", "title"), name="unique_topic_title_per_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("topic", "title", "variant"),
                name="unique_lesson_title_variant_per_topic",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitlesson",
            constraint=models.UniqueConstraint(
                fields=("unit", "lesson"), name="unique_unit_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitlesson",
            constraint=models.UniqueConstraint(
                fields=("unit", "order"), name="unique_lesson_order_per_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "year_group", "level", "order"),
                name="unique_unit_per_curriculum_year_level_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 1), ("order__lte", 6)),
                name="unit_order_between_1_and_6",
            ),
        ),
    ]
