# Generated by Django 5.2.12 on 2026-04-06 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "lesson_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "resource_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("slide", "Slide"),
                            ("worksheet", "Worksheet"),
                            ("video", "Video"),
                            ("template", "Template"),
                            ("file", "File"),
                            ("link", "Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "category"],
            },
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_resources",
                        to="core.lesson",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_lessons",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="resources",
            field=models.ManyToManyField(
                related_name="lessons",
                through="core.LessonResource",
                to="core.resource",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("slug", models.SlugField(blank=True)),
                ("level", models.CharField(choices=[("gcse", "GCSE")], max_length=5)),
                (
                    "language",
                    models.CharField(choices=[("en", "English")], max_length=5),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "level", "language"),
                        name="unique_subject_title_level_language",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "title"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="core.topic",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonresource",
            constraint=models.UniqueConstraint(
                fields=("lesson", "resource"), name="unique_lesson_resource"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("subject", "title"), name="unique_topic_title_per_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("topic", "title"), name="unique_lesson_title_per_topic"
            ),
        ),
    ]
