# Generated by Django 5.2.12 on 2026-05-16 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonName",
            fields=[
                (
                    "lesson_name_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("is_protected", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="LessonVariant",
            fields=[
                (
                    "lesson_variant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300)),
                ("is_published", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_variants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_variants",
                        to="core.lessonname",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "topic", "lesson_name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "resource_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("slide", "Slide"),
                            ("worksheet", "Worksheet"),
                            ("video", "Video"),
                            ("template", "Template"),
                            ("file", "File"),
                            ("link", "Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("is_protected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title", "category"],
            },
        ),
        migrations.CreateModel(
            name="LessonVariantResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_variant_resources",
                        to="core.lessonvariant",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_lesson_variants",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson_variant", "order"],
            },
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="resources",
            field=models.ManyToManyField(
                related_name="lesson_variants",
                through="core.LessonVariantResource",
                to="core.resource",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=500)),
                (
                    "level",
                    models.CharField(
                        choices=[("secondary", "Secondary"), ("primary", "Primary")],
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(choices=[("en", "English")], max_length=2),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "level", "language"),
                        name="unique_subject_title_level_language",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="subjects",
            field=models.ManyToManyField(related_name="resources", to="core.subject"),
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variants",
                to="core.subject",
            ),
        ),
        migrations.AddField(
            model_name="lessonname",
            name="subjects",
            field=models.ManyToManyField(
                related_name="lesson_names", to="core.subject"
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, max_length=500)),
                ("is_protected", models.BooleanField(default=False)),
                (
                    "subjects",
                    models.ManyToManyField(related_name="topics", to="core.subject"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variants",
                to="core.topic",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonvariantresource",
            constraint=models.UniqueConstraint(
                fields=("lesson_variant", "resource"),
                name="unique_lesson_variant_resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonname",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_lesson_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_topic_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonvariant",
            constraint=models.UniqueConstraint(
                fields=("subject", "topic", "lesson_name"),
                name="unique_variation_per_lesson_name",
            ),
        ),
    ]
