# Generated by Django 5.2.12 on 2026-04-09 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonName",
            fields=[
                (
                    "lesson_name_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="LessonVariant",
            fields=[
                (
                    "lesson_variant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "subject",
                    "topic",
                    "lesson_name",
                    "teaching_style",
                    "variation",
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonVariantResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["lesson_variant", "order"],
            },
        ),
        migrations.CreateModel(
            name="TeachingStyle",
            fields=[
                (
                    "teaching_style_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "variation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="curriculum",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="resources",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="unitlesson",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonresource",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="lessons",
        ),
        migrations.RemoveField(
            model_name="lessonresource",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="unitlesson",
            name="unit",
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveConstraint(
            model_name="topic",
            name="unique_topic_title_per_subject",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="description",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="subject",
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="subject",
            name="slug",
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_topic_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonname",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_lesson_title"
            ),
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="lesson_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variants",
                to="core.lessonname",
            ),
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variants",
                to="core.subject",
            ),
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variants",
                to="core.topic",
            ),
        ),
        migrations.AddField(
            model_name="lessonvariantresource",
            name="lesson_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variant_resources",
                to="core.lessonvariant",
            ),
        ),
        migrations.AddField(
            model_name="lessonvariantresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_lesson_variants",
                to="core.resource",
            ),
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="resources",
            field=models.ManyToManyField(
                related_name="lesson_variants",
                through="core.LessonVariantResource",
                to="core.resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingstyle",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_teaching_style_title"
            ),
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="teaching_style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variants",
                to="core.teachingstyle",
            ),
        ),
        migrations.AddConstraint(
            model_name="variation",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_variation_title"
            ),
        ),
        migrations.AddField(
            model_name="lessonvariant",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_variants",
                to="core.variation",
            ),
        ),
        migrations.DeleteModel(
            name="Curriculum",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="LessonResource",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
        migrations.DeleteModel(
            name="UnitLesson",
        ),
        migrations.AddConstraint(
            model_name="lessonvariantresource",
            constraint=models.UniqueConstraint(
                fields=("lesson_variant", "resource"),
                name="unique_lesson_variant_resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonvariant",
            constraint=models.UniqueConstraint(
                fields=(
                    "subject",
                    "topic",
                    "lesson_name",
                    "teaching_style",
                    "variation",
                ),
                name="unique_variation_per_lesson_name",
            ),
        ),
    ]
