# Generated by Django 5.2.12 on 2026-04-07 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "curriculum_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["subject", "title"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "unit_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year_group",
                    models.CharField(
                        choices=[
                            ("year_7", "Year 7"),
                            ("year_8", "Year 8"),
                            ("year_9", "Year 9"),
                            ("year_10", "Year 10"),
                            ("year_11", "Year 11"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("core", "Core"),
                            ("red", "Red"),
                            ("amber", "Amber"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("mixed_ability", "Mixed Ability"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["curriculum", "year_group", "level", "order"],
            },
        ),
        migrations.CreateModel(
            name="UnitLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["unit", "order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="lesson",
            name="unique_lesson_title_per_topic",
        ),
        migrations.AddField(
            model_name="lesson",
            name="variant",
            field=models.CharField(
                choices=[("base", "Base"), ("no_negatives", "No Negatives")],
                default="base",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="resource",
            name="slug",
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="language",
            field=models.CharField(choices=[("en", "English")], max_length=2),
        ),
        migrations.AlterField(
            model_name="subject",
            name="level",
            field=models.CharField(choices=[("gcse", "GCSE")], max_length=10),
        ),
        migrations.AlterField(
            model_name="subject",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("topic", "title", "variant"),
                name="unique_lesson_title_variant_per_topic",
            ),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculums",
                to="core.subject",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="curriculum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="core.curriculum",
            ),
        ),
        migrations.AddField(
            model_name="unitlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_units",
                to="core.lesson",
            ),
        ),
        migrations.AddField(
            model_name="unitlesson",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_lessons",
                to="core.unit",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="lessons",
            field=models.ManyToManyField(
                related_name="units", through="core.UnitLesson", to="core.lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculum",
            constraint=models.UniqueConstraint(
                fields=("subject", "title"), name="unique_curriculum_title_per_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitlesson",
            constraint=models.UniqueConstraint(
                fields=("unit", "lesson"), name="unique_unit_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitlesson",
            constraint=models.UniqueConstraint(
                fields=("unit", "order"), name="unique_lesson_order_per_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "year_group", "level", "order"),
                name="unique_unit_per_curriculum_year_level_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 1), ("order__lte", 6)),
                name="unit_order_between_1_and_6",
            ),
        ),
    ]
