# Generated by Django 5.2.12 on 2026-04-08 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="is_published",
        ),
    ]
