# Generated by Django 5.2.12 on 2026-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonname",
            name="subjects",
            field=models.ManyToManyField(
                related_name="lesson_names", to="core.subject"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="subjects",
            field=models.ManyToManyField(related_name="resources", to="core.subject"),
        ),
        migrations.AddField(
            model_name="topic",
            name="subjects",
            field=models.ManyToManyField(related_name="topics", to="core.subject"),
        ),
    ]
