# Generated by Django 5.2.12 on 2026-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_lessonname_subjects_resource_subjects_topic_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="level",
            field=models.CharField(
                choices=[("secondary", "Secondary"), ("primary", "Primary")],
                max_length=10,
            ),
        ),
    ]
